import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="">
      <body className={inter.className + " bg-slate-200"}>
        <div className="w-full bg-slate-900 text-white gap-5 flex p-3 font-gothic">
          <Link className="" href="/">
            메인
          </Link>
          <Link href="/list">상품목록</Link>
          <Link href="/cart">장바구니</Link>
          <Link href="/board">게시판</Link>
        </div>
        <div className="mt-10 justify-center flex h-screen max-h-[600px] min-w-[1000px]">
          <div className=" bg-slate-50 w-4/5 rounded-lg shadow-lg p-4 font-gothic">{children}</div>
        </div>
      </body>
    </html>
  );
}
